=== olexandryermilov/FileCommander1/facultySoftwareDatabase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.w3schools.com"
           xmlns="https://www.w3schools.com"
           elementFormDefault="qualified">
    <xsd:element name="facultySoftwareDatabase" type="facultySoftwareDatabaseType"/>
<xsd:complexType name="facultySoftwareDatabaseType">
    <xsd:sequence>
        <xsd:element name="software" minOccurs="1" maxOccurs="unbounded">
            <xsd:complexType>
                <xsd:sequence>
                    <xsd:element name="type" type="xsd:string"/>
                    <xsd:element name="author" type="xsd:string"/>
                    <xsd:element name="license" type="xsd:string"/>
                </xsd:sequence>
                <xsd:attribute name="name" type="xsd:string"/>
                <xsd:attribute name="description" type="xsd:string"/>
                <xsd:attribute name="version" type="xsd:string"/>
            </xsd:complexType>
        </xsd:element>
    </xsd:sequence>
</xsd:complexType>
</xsd:schema>

=== olexandryermilov/FileCommander1/facultyDatabase.xml
<?xml version = "1.0" encoding="UTF-8"?>

<facultySoftwareDatabase xmlns="https://www.w3schools.com"
                         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xsi:schemaLocation="facultySoftwareDatabase.xsd">
	<software name = "Windows"
		description = "Operation system for students and educators"
		version = "10.0">
		<type>OS</type>
		<author>Microsoft</author>
		<license>educational</license>
	</software>
	<software name = "WolframAlpha"
		description = "Advanced calculator for students"
		version = "1.03">
		<type>Calculator</type>
		<author>Wolfram</author>
		<license>educational</license>
	</software>
	<software name = "VisualStudio"
		description = "IDE for C#, C++, C and Basic"
		version = "17">
		<type>IDE</type>
		<author>Microsoft</author>
		<license>free</license>
	</software>
	<software name = "Intellij Idea"
		description = "IDE for JVM-based languages"
		version = "17.3">
		<type>IDE</type>
		<author>JetBrains</author>
		<license>paid</license>
	</software>
	<software name = "PyCharm"
		description = "IDE for Python"
		version = "17.2">
		<type>IDE</type>
		<author>JetBrains</author>
		<license>paid</license>
	</software> 
</facultySoftwareDatabase>
